---
title: "R Notebook"
output: html_notebook
---

```{r}
require(ggplot2)
require(dplyr)
require(data.table)
require(tidyr)
require(stringr)
require(tools)
```


```{r}
process_file <- function(filename) {
  raw_positions <- fread(filename)

  positions <- raw_positions %>% mutate(
    value = price * num_shares,
    type = ifelse(tkr == 'CASH','CASH','STOCK')
  ) 

  # Extract extra information from filename 
  #
  filename_data <- file_path_sans_ext(basename(filename))
  strategy <- ''
  for(item in str_split(filename_data,"-")[[1]]) {
    tokens <- str_split(str_replace(item,"]",""),"\\[")
    for(token in tokens) {
      if(token[1]=='strategy') {
        strategy <- token[2]
      }
      positions <- positions %>% mutate("{token[1]}":=token[2])  
    }
  }

  pg <- positions %>% group_by(date,type) %>% summarise(v = sum(value))
  value_per_day <- positions %>% group_by(date) %>% summarise(v = sum(value))
  
  pl <- ggplot(pg,aes(x=date,y=v,fill=type)) + geom_bar(stat = "identity") + ggtitle(filename_data)
  
  pl2 <- ggplot(value_per_day,aes(x=date,y=v)) +geom_line() + ggtitle(filename_data) +ylim(0,100000)
  
  
  return(list(pl,positions,strategy,pl2))
}


print(process_file("../strategy[daily_range_breakout]-window[3]-stop_loss_perc[0.05].csv")[[1]])
print(process_file("../strategy[daily_range_breakout]-window[3]-stop_loss_perc[0.05].csv")[[2]])
print(process_file("../strategy[daily_range_breakout]-window[3]-stop_loss_perc[0.05].csv")[[3]])
print(process_file("../strategy[daily_range_breakout]-window[3]-stop_loss_perc[0.05].csv")[[4]])

```

```{r}
results_path = "../results"
result_files <- list.files(path = results_path, pattern = "*.csv")
for(result_file in result_files) {
  result <- process_file(file.path(results_path,result_file))
  print(result[[4]])
  
}

```

